version: '3.9'
services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ContestDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 228Gtnhjd228
    ports:
      - "5433:5432"



