# Generated by Django 5.0.1 on 2024-02-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel',
            table='test',
        ),
    ]
