# Generated by Django 5.0.1 on 2024-02-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestApp', '0002_alter_testmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptmodel',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ContestApp.profilemodel'),
        ),
        migrations.AlterField(
            model_name='attemptmodel',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ContestApp.taskmodel'),
        ),
        migrations.AlterField(
            model_name='solutionmodel',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ContestApp.taskmodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ContestApp.profilemodel'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ContestApp.taskmodel'),
        ),
    ]
