# Generated by Django 5.0.1 on 2024-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestApp', '0005_alter_attemptmodel_profile_alter_attemptmodel_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='test_number',
            field=models.IntegerField(null=True),
        ),
    ]
