# Generated by Django 5.0.1 on 2024-03-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestApp', '0008_solutionmodel_passed_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
