# Generated by Django 5.0.1 on 2024-03-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestApp', '0009_taskmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionmodel',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
