# Generated by Django 5.0.1 on 2024-05-08 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestApp', '0011_taskmodel_sent_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(blank=True, default='My description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='langs',
            field=models.CharField(default='C|C++|Python|Java', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='owner',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='ContestApp.profilemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(blank=True, default='My title', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AttemptModel',
        ),
    ]
