# Generated by Django 5.0.1 on 2024-05-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestApp', '0012_alter_taskmodel_description_alter_taskmodel_langs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
