# Generated by Django 5.0.1 on 2024-05-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestApp', '0013_alter_taskmodel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionmodel',
            name='status',
            field=models.CharField(choices=[('passed', 'passed'), ('failed', 'failed')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='status',
            field=models.CharField(choices=[('passed', 'passed'), ('failed', 'failed')], max_length=16, null=True),
        ),
    ]
