name: Django CI

on:
  push:
    branches: [ "Contest" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Backend
      run: |
        python manage.py runserver
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: gradle/actions@v3.3.2
    - name: Build with Gradle
      run: |
        gradle build test
       
 
  
          

        
