name: Django CI

on:
  push:
    branches: [ "Contest" ]
    
  pull_request:
    branches: ["main"]

jobs:
  backend-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build backend with database
      uses: hoverkraft-tech/compose-action@v2.0.0
      with:
        compose-file: "./backend/ContestAPI/docker-compose.yml"
        
  java-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'

    - name: Build and Test Java Project
      run: |
        cd tests
        ./gradlew clean --no-daemon
        ./gradlew test --no-daemon

    - name: Install Allure command-line tool
      run: |
        sudo apt-add-repository ppa:qameta/allure
        sudo apt-get update
        sudo apt-get install allure -y

    - name: Generate Allure Report
      run: |
        cd tests
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: ./tests/allure-report
       
 
  
          

        
